package com.alcozone.application.mapper;

import com.alcozone.application.dto.dashboard.CreateDashboardDTO;
import com.alcozone.application.dto.dashboard.UpdateDashboardDTO;
import com.alcozone.domain.models.Dashboard;

import java.time.LocalDateTime;
import java.util.UUID;

public class DashboardDTOMapper {

    public static Dashboard fromCreateDTO(CreateDashboardDTO dto) {
        return new Dashboard(
                0, // ID will be generated by the DB
                UUID.randomUUID().toString().replace("-", ""),
                dto.getUserUuid(),
                dto.getName(),
                LocalDateTime.now(),
                LocalDateTime.now()
        );
    }

    public static Dashboard fromUpdateDTO(UpdateDashboardDTO dto, Dashboard existing) {
        existing.setName(dto.getName());
        existing.setUpdatedAt(LocalDateTime.now());
        return existing;
    }
}
